name: CI/CD

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

env: 
  IMAGE: issakhrorov/demo-infra
  
jobs:
  build-test:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.getsha.outputs.shortsha }}
    steps:  
      - uses: actions/checkout@v4
      
      - name: Get short SHA
        id: getsha
        run: echo "shortsha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT 
        
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          
      - name: Run unit tests
        run: ./gradlew clean test --no-daemon

  build-and-push:
    needs: build-test
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          TAG=${{ needs.build-test.outputs.sha }}
          docker build -t $IMAGE:$TAG .
          docker tag $IMAGE:$TAG $IMAGE:latest

      - name: Push image
        run: |
          TAG=${{ needs.build-test.outputs.sha }}
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: main
    steps: 
      - name: Deploy to server over SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script: |
            bash "/Users/akhrorovismoil/Desktop/SR Projects/DemoInfraPortfolio/SERVER/deploy-local.sh" ${{ needs.build-test.outputs.sha }}
      
          
