name: CI
permissions:
  contents: write

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

env: 
  IMAGE: issakhrorov/demo-infra
  
jobs:
  build-test:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.getsha.outputs.shortsha }}
    steps:  
      - uses: actions/checkout@v4
      
      - name: Get short SHA
        id: getsha
        run: echo "shortsha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT 
        
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          
      - name: Run unit tests
        run: ./gradlew clean test --no-daemon

  build-and-push:
    needs: build-test
    runs-on: ubuntu-latest
    environment: main
    outputs: 
      image_tag: ${{ steps.settag.outputs.tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: settag
        run: |
          TAG="user-service-${{ needs.build-test.outputs.sha }}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Docker tag set to $TAG"

      - name: Build image
        run: |
          TAG="user-service-${{ needs.build-test.outputs.sha }}"
          docker build -t $IMAGE:$TAG .
          docker tag $IMAGE:$TAG $IMAGE:user-service

      - name: Push image
        run: |
          TAG="user-service-${{ needs.build-test.outputs.sha }}"
          docker push $IMAGE:$TAG
          docker push $IMAGE:user-service

#  deploy:
#    needs: build-and-push
#    runs-on: self-hosted
#    environment: main
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Debug workspace
#        run: |
#          pwd
#          ls -R
#
#      - name: Run local deploy script
#        working-directory: ${{ github.workspace }}
#        run: bash "/Users/akhrorovismoil/Desktop/SR_Projects/DemoInfraPortfolio/SERVER/deploy-local.sh"

  update-helm:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout Help repo
        uses: actions/checkout@v4
        with:
          repository: issakhrorov/demo-infra-helm
          token: ${{ secrets.PAT_GITHUB }}
          path: helm

      - name: Show tag passed from build and push
        run: echo "user-service-${{ needs.build-and-push.outputs.image_tag }}"

      - name: Update image tag in Helm values.yaml
        run: |
          cd helm/user
          TAG="user-service-${{ needs.build-and-push.outputs.image_tag }}"
          echo "Updating tag to: $TAG"
          yq e -i ".image.tag = \"$TAG\"" values.yaml

      - name: Commit and push Helm update
        run: |
          cd helm/user
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@users.noreply.github.com"
          git add .
          git commit -m "Update user-service image tag to $TAG" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PAT_GITHUB }}@github.com/issakhrorov/demo-infra-helm.git main
