name: PR checks

on:
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: ~/.gradle
          key: ${{runner.os}}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Run unit tests
        run: ./gradlew test --no-deamon
